#!/bin/bash
echo "$0 $1"
echo "    "
echo "Generating Stats for dev1.devopscave.com"
echo "****************************************************"
echo "Server Name: dev1.devopscave.com"

echo "OS Details:"
echo "------------"
echo "     "
echo "OS Type:`uname`"
echo "OS Flavor: `cat /etc/redhat-release|cut -c1-6`"
echo "OS Version: ` cat /etc/redhat-release|cut -d " " -f4`"
echo "32 bit or 64 bit:`uname -m`"
echo "    "
echo "CPU Details:"
echo "----------------"
echo "CPU Vendor: `cat /proc/cpuinfo|grep vendor|head -1|cut -d " " -f2`"
var3=`cat /proc/cpuinfo|grep processor|wc -l`
echo "Number of Processors: $var3"
echo "Model Name:`cat /proc/cpuinfo|grep model|head -2|tail -1|cut -c14-55`"
var=`cat /proc/cpuinfo|grep cpu|head -3|tail -1|cut -c13`
echo "Total number of Cores: $((var*var3))"
echo "              "
echo "Memory Details:"
echo "---------------------"
echo "Total Memory : `free|head -2|tail -1|cut -d " " -f9`"
echo "Memory available: `free|head -2|tail -1|cut -d " " -f19`"
echo "Memory used: `free|head -2|tail -1|cut -d " " -f14`"
echo "Total Swap memory: `free|tail -1|cut -d " " -f14`"
echo "   "
echo "Disk details:"
echo "----------------"
echo "Total disk space: `df -h|head -2|tail -1|cut -d ' ' -f8`"
echo "Disk space available: `df -h|head -2|tail -1|cut -d ' ' -f14`"
echo "Disk space used: `df -h|head -2|tail -1|cut -d ' ' -f11`"
echo "Usage percentage: `df -h|head -2|tail -1|cut -d ' ' -f16`"
echo "           "
echo "Users Details:"
echo "------------------"
echo "Total number of users: `less /etc/passwd|cut -d " " -f1|sort|wc -w`"
echo "Total number of real users: `less /etc/passwd|grep /bin/bash|wc -l`"


