#!/bin/bash
echo "$0 $1"
echo "Generating stats for dev1.devopscave.com"
echo "****************************************"
echo "Server Name:dev1.devopscave.com"
echo "                              "
echo "OS Details:"
echo "-----------"
echo "OS type:`uname`"
echo "OS Flavor:`cat /etc/redhat-release|cut -d ' ' -f1`"
echo "OS Version:`cat /etc/redhat-release|cut -d ' ' -f4`"
echo "32 bit or 64 bit:`uname -p|cut -d '_' -f2`"
echo "                              "
echo "CPU Details"
echo "---------------"
echo "CPU Vendor:`less /proc/cpuinfo|grep vendor_id|head -1|cut -d ':' -f2`"
echo "Number of Processors:`less /proc/cpuinfo|grep processor|wc -l`"
echo "Model Name:`less /proc/cpuinfo|grep model|head -2|tail -1`"
echo "Total number of Cores:`less /proc/cpuinfo|grep cpu|cut -d ':' -f2|head -3|tail -1`*4"
echo "                              "
echo "Memory Details:"
echo "---------------------"
echo "Total Memory :`free|cut -d ':' -f 2|tail -2|head -1|cut -d ' ' -f9`"
echo "Memory available:`free|cut -d ':' -f 2|tail -2|head -1|cut -d ' ' -f37`"
echo "Memory used:`free|cut -d ':' -f 2|tail -2|head -1|cut -d ' ' -f14`" 
echo "Total Swap memory:`free|cut -d ':' -f 2|tail -1|cut -d ' ' -f14`"
echo "                              "
echo "Disk details:"
echo "----------------"
echo "Total disk space:`df -h|head -2|tail -1|cut -d ' ' -f8`"
echo "Disk space available:`df -h|head -2|tail -1|cut -d ' ' -f14`"
echo "Disk space used:`df -h|head -2|tail -1|cut -d ' ' -f11`"
echo "Usage percentage:`df -h|head -2|tail -1|cut -d ' ' -f16`"
echo "                              "
echo "Users Details:"
echo "------------------"
echo "Total number of users:`less /etc/passwd|cut -d ' ' -f1|sort|wc -w`"
echo "Total number of real users:`less /etc/passwd|grep bin/bash|wc -l`"
